class Level1:
    class Level2:
        class Level3:
            class Level4:
                def level4_method(self):
                    if True:
                        if True:
                            if True:
                                return "deep"